basePath: /api/v1
definitions:
  model.MessageResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      is_sent:
        type: boolean
      message_id:
        type: string
      phone_number:
        type: string
      sent_at:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for automatic message sending system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Insider Message Sending API
  version: "1.0"
paths:
  /messages/sent:
    get:
      consumes:
      - application/json
      description: Get a list of all sent messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.MessageResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get sent messages
      tags:
      - messages
  /messages/start:
    post:
      consumes:
      - application/json
      description: Start the automatic message sending process
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Start automatic message sending
      tags:
      - messages
  /messages/stop:
    post:
      consumes:
      - application/json
      description: Stop the automatic message sending process
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Stop automatic message sending
      tags:
      - messages
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
